PROCESS BEFORE OUTPUT.
  MODULE status_0100.

PROCESS AFTER INPUT.
  MODULE exit_0100 AT EXIT-COMMAND.
  MODULE user_command_0100.

PROCESS ON VALUE-REQUEST.
  FIELD gv_choice MODULE f4_choice.

PROCESS ON HELP-REQUEST.
  FIELD gv_choice MODULE f1_choice.
